### ISSUE TITLE
How can I get image data to upload to my server?

### ISSUE THREAD

**Issue by ahmadkam72** [JakeHartnell/react-images-upload#109]
I get image files array that contain name, type, size, lastModifiedDate, lastModified and
webkitRelativePath .
I want to upload selected image to my server and I need image data to do this.
If any other method exists to do this, please help me
Thank you.

**Comment by nql5161** [comment]
Also having this problem. Did you happen to resolve it? Looking forward to your reply.

**Comment by easikoglu** [comment]
when you get pictureFiles at onDrop function, set them to state and in your handleSubmit function use this file array, 
You can use formData object to send file to server as File Object.
`handleSubmit() {
    
    let formData = new FormData();
    formData.append('photo', this.state.files[0]);
    
    fetch('http://myuploadserver', { // Your POST endpoint
        method: 'POST',
        body: formData
    }).then(
        response => response.json() // if the response is a JSON object
    ).then(
        //TODO:save also in customer object
        success => console.log(success) // Handle the success response object
    ).catch(
        error => console.log(error) // Handle the error response object
    );
    
}`

**Comment by han-so1omon** [comment]
I think there should be documentation or a link to documentation on the way that the images are subsequently stored. I am having trouble with this same issue.

**Comment by ivnnv** [comment]
Hi,
There are a million ways images can be stored in a server and thats completely out of the scope of this library, hence closing as unrelated.

**Comment by han-so1omon** [comment]
@ivnnv I mean the way that images are stored in-memory, client-side javascript immediately after pressing the upload button. Are there multiple ways for different browsers or does in-memory storage always use File API? If so please include a note or link to the File API, as it was not immediately clear to me how to use the image.
