### ISSUE TITLE
How to restrict to one file?

### ISSUE THREAD

**Issue by cristian-milea** [JakeHartnell/react-images-upload#11]
Is there any attr for single file?

**Comment by IvanLinos** [comment]
This is what i did to get Single Image option functionality on the component (so you can use it or not when initialising):

Added prop on: _ReactImageUploadComponent.defaultProps_
`singleImage: false`
Added prop type on: _ReactImageUploadComponent.PropTypes_
`singleImage: PropTypes.bool`

And then rewrote function render.onload like this:
`reader.onload = function () {
    return function (e) {
        if (_this.props.singleImage === true) {
            _this.setState({ pictures: [e.target.result] });
        } else if (_this.state.pictures.indexOf(e.target.result) === -1) {
            var _newArray2 = _this.state.pictures.slice();
            _newArray2.push(e.target.result);
            _this.setState({ pictures: _newArray2 });
        }
    };
}(f);`

@JakeHartnell could you please add this as a new feature? Thanks!

**Comment by JakeHartnell** [comment]
Thanks for the code snippet @IvanLinos, I'll add this soon.

**Comment by IvanLinos** [comment]
Hi @JakeHartnell i finally had the time to properly fork the project and create a pull request for the component and the demo app/documentation , please test it when you have time :)

**Comment by JakeHartnell** [comment]
Thanks @IvanLinos for the PR, version 1.0.5 is published: https://www.npmjs.com/package/react-images-upload
