### ISSUE TITLE
how to find width and height of an image?

### ISSUE THREAD

**Issue by reckinam** [JakeHartnell/react-images-upload#115]
i need to restrict the image ,based on the dimension.I could not find documentation to find height and width of an image.

**Comment by deveshlashkari** [comment]
+1

> i need to restrict the image ,based on the dimension.I could not find documentation to find height and width of an image.

**Comment by Devang142** [comment]
+1

**Comment by ivnnv** [comment]
Closing as not related.
You should check image dimensions by yourself with standard javascript or some other library.
