### ISSUE TITLE
Allow animation to be disabled.

### ISSUE THREAD

**Issue by imedmar** [JakeHartnell/react-images-upload#116]
Currently when a file is uploaded or removed, there's a cool fade in and out animation.  
Problem with this feature is that it might cause some weird component resizing. 

Here's an example:
![disable_anim](https://user-images.githubusercontent.com/1714122/68533345-68664f80-02f5-11ea-903f-a5175ec2eebd.gif)

That said, I think the animation should be configurable.

**Comment by ivnnv** [comment]
The animation only "animates" the container, removing the animation wont solve the resizing.

You have two options if you don't want the "weird resizing" to happen:
1) Completely remove the image preview with the "withPreview=false" prop.
2) Add a height css property to the image container / the whole component.
- Take into account that there could be many images so we cant make a general solution for this "problem". You need to address it for your specific use case, for example setting the image container height to a fixed 250px.
