### ISSUE TITLE
Proptype validation

### ISSUE THREAD

**Issue by MarkAPhillips** [JakeHartnell/react-images-upload#13]
`ReactImageUploadComponent.PropTypes = {`

should be `ReactImageUploadComponent.propTypes = {`

an error is thrown in the console currently

**Comment by tareq0065** [comment]
Same problem I am getting also. I changed `ReactImageUploadComponent.PropTypes = {` to `ReactImageUploadComponent.propTypes = {`. But its nt working.

Warning: Component ReactImageUploadComponent declared `PropTypes` instead of `propTypes`. Did you misspell the property assignment?

**Comment by JakeHartnell** [comment]
Fixed with 1.0.3.
