### ISSUE TITLE
Heroku demo link doesn't work

### ISSUE THREAD

**Issue by Aarbel** [JakeHartnell/react-images-upload#139]
https://ancient-refuge-49866.herokuapp.com/

![image](https://user-images.githubusercontent.com/25119847/73590329-88b33e00-44e1-11ea-9585-480fe1c9d04f.png)

**Comment by ivnnv** [comment]
Ideally we should host this demo on github pages.
@JakeHartnell if you grant me this kind of access on the repo I could do it.

**Comment by JakeHartnell** [comment]
@ivnnv awesome! I've enabled gh-pages and pointed it towards the `gh-pages` branch: https://jakehartnell.github.io/react-images-upload/

You should be able to push to that branch.

I have been really busy with some other projects recently, so sorry for the slow response.

**Comment by JakeHartnell** [comment]
Demo app: https://jakehartnell.github.io/react-images-upload/
