### ISSUE TITLE
Does this library support browser image resize if the image is too big ?

### ISSUE THREAD

**Issue by Aarbel** [JakeHartnell/react-images-upload#140]
Does this library support browser image resize if the image is too big, before sending this image to server ?

The problem becomes to be a big thing with high resolution mobile photos.

Here is a feed about it:
https://stackoverflow.com/questions/10333971/html5-pre-resize-images-before-uploading

**Comment by ivnnv** [comment]
You should check and do the relevant operations by yourself inside the `onDrop` event and before you upload it to the server.

**Comment by Aarbel** [comment]
Thanks a lot @ivnnv, ifound this instead: https://www.npmjs.com/package/browser-image-resizer
