### ISSUE TITLE
How do I get the URL of the upload?

### ISSUE THREAD

**Issue by DanielSalazar1** [JakeHartnell/react-images-upload#152]
Hello.

I'm using your library and I uploaded the image. I want to get the URL in my local, how do I do that?

**Comment by Louie-Healthsite** [comment]
@DanielSalazar1 
I'm using URL.createObjectURL - see code below
onDrop(picture) {
    if (picture[0]) {
      const newPicURL = URL.createObjectURL(picture[0]);
      this.setState({
        picture: picture, // This is the object
        newPicURL: newPicURL, // This is the local URL
      }, () => this.props.callbackHandler("SELECT_IMAGE", picture));
    }
  }

You can then use **newPicURL** as the source of the image within render; I'm doing this
const pic = this.state.picture.length > 0 ? this.state.newPicURL : this.props.picture;
