### ISSUE TITLE
Prop to support Upload from Camera

### ISSUE THREAD

**Issue by iamchathu** [JakeHartnell/react-images-upload#155]
Can we pass input props to open camera to take picture?

**Comment by ivnnv** [comment]
Mobile OS's already provide that feature automatically

![takepic or select](https://user-images.githubusercontent.com/23552631/78043301-78013600-7373-11ea-94ea-c7c0b02df50f.png)

**Comment by iamchathu** [comment]
@ivnnv  Can we set default camera like `capture="environment"` ?
