### ISSUE TITLE
Global CSS cannot be imported from within node_modules at nextJs

### ISSUE THREAD

**Issue by kuzanto** [JakeHartnell/react-images-upload#176]
hello,

I use next js for my apps and when  want to use import this library i get this error.
```

./node_modules/react-images-upload/index.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules\react-images-upload\compiled.js

```
anyone can help?

Thank you,
Regard

**Comment by PabloZarate01** [comment]
I've the same issue, any solution?

**Comment by kuzanto** [comment]
> I've the same issue, any solution?

I change to another library because not found any solution for now.

**Comment by PabloZarate01** [comment]
Same!

**Comment by malithmcr** [comment]
Try  with next.config.js

// next.config.js 
const withCSS = require('@zeit/next-css');

module.exports = withCSS({
  cssLoaderOptions: {
    url: false
  }
});

**Comment by mathiasfc** [comment]
Same here :| 

> > I've the same issue, any solution?
> 
> I change to another library because not found any solution for now.

can you share the library you are using now?

**Comment by kuzanto** [comment]
> Same here :|
> 
> > > I've the same issue, any solution?
> > 
> > 
> > I change to another library because not found any solution for now.
> 
> can you share the library you are using now?

hi, I use https://github.com/react-dropzone/react-dropzone for now. I hope it's can help

**Comment by kuzanto** [comment]
> Try with next.config.js
> 
> // next.config.js
> const withCSS = require('@zeit/next-css');
> 
> module.exports = withCSS({
> cssLoaderOptions: {
> url: false
> }
> });

I already tried that before but still get error.
