### ISSUE TITLE
"Choose images" button type should be configurable

### ISSUE THREAD

**Issue by donalmurtagh** [JakeHartnell/react-images-upload#32]
The "choose images" button does not have a `type` attribute. A consequence of this is that when the `ImageUploader` is used within a `<form>`, clicking on this button causes the form to be submitted (because the default type of a button in a form is a submit button).

It should be possible to configure the button type via a prop, so that it can be changed to (for example) `<button type="button">` which would not submit a form when clicked.

**Comment by MikeKotte** [comment]
Thanks for changing this! Any indication when the npm package will be updated to include the recent changes?

**Comment by donalmurtagh** [comment]
@MikeKotte I don't have permission to do releases, you'll have to ask @JakeHartnell
