### ISSUE TITLE
Image to Base64 format 

### ISSUE THREAD

**Issue by shashankcm** [JakeHartnell/react-images-upload#42]
can you help me to convert images to base64 formate using this package?

**Comment by donalmurtagh** [comment]
This package already converts the uploaded images to base64, here is [the relevant code](https://github.com/JakeHartnell/react-images-upload/blob/master/src/component/index.js#L106L116)

**Comment by usmanzia7864561** [comment]
On drop function return two values first file details and second base64 url
Example here
const onDrop = (pictureFiles, pictureDataURLs) => {

}
