### ISSUE TITLE
Form submit trigger

### ISSUE THREAD

**Issue by Boussama** [JakeHartnell/react-images-upload#43]
When put inside a form, the click on the upload button trigger the submit functionality.

**Comment by donalmurtagh** [comment]
Currently, the default value for the `buttonType` prop is `"submit"`, so if you don't set this prop (or set it to `"submit"`), the form _will_ be submitted when the upload button is clicked.

**Comment by Boussama** [comment]
NLTD: we should not create modules that doesn't work well with other components.
I think that this should work in general condition, which is that an input is a part from a form.
Thus this component should not submit a form by default but instead act as a simple input.
This is why it's an issue.

**Comment by donalmurtagh** [comment]
@Boussama I agree that using `submit` as the default type for the `input` was not the best choice. However, if we were to change this default now, it would introduce an avoidable breaking change.
