### ISSUE TITLE
multiple image selection when singleImage is true

### ISSUE THREAD

**Issue by Boussama** [JakeHartnell/react-images-upload#45]
Wrong behavior, when singleImage is true user should not be able to select multiple image to upload, not just on the component UI.

**Comment by donalmurtagh** [comment]
This is a duplicate of #53. I've submitted a PR to fix this #54

**Comment by Boussama** [comment]
This issue was submitted first and can't be a duplicate to a new issue.

**Comment by donalmurtagh** [comment]
@Boussama by "duplicate", I mean they are both covering the same topic

**Comment by brionmario** [comment]
Is this fixed yet? I have the version 1.2.0 and the issue is still there.
