### ISSUE TITLE
Preview is not showing like the Demo example.

### ISSUE THREAD

**Issue by AikoRamalho** [JakeHartnell/react-images-upload#48]
For some reason my image uploader is not showing the image's preview. 

I created my example using react-create-app and just copy and paste the example instalation in my App.js file.

Here is my package.json

{
  "name": "teste",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.4.0",
    "react-dom": "^16.4.0",
    "react-flip-move": "^3.0.2",
    "react-images-upload": "^1.1.99",
    "react-scripts": "1.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

and my App.js:

import React from 'react';
import ImageUploader from 'react-images-upload';
 
class App extends React.Component {
 
    constructor(props) {
        super(props);
         this.state = { pictures: [] };
         this.onDrop = this.onDrop.bind(this);
    }
 
    onDrop(picture) {
        this.setState({
            pictures: this.state.pictures.concat(picture),
        });
    }
 
    render() {
        return (
            <ImageUploader
                withIcon={true}
                buttonText='Choose images'
                onChange={this.onDrop}
                imgExtension={['.jpg', '.gif', '.png', '.gif']}
                maxFileSize={5242880}
            />
        );
    }
}

export default App;

**Comment by AikoRamalho** [comment]
Ah, the picture's state is working just fine, it's appending the upload picture correctly.

**Comment by AikoRamalho** [comment]
Im an idiot. I didn't read the doc well, it was just add a "withPreview={true}" in the ImageUploader component.

Sorry, i'm closing it.

**Comment by JakeHartnell** [comment]
@AikoRamalho, glad you figured it out. : )
