### ISSUE TITLE
How do you reset this component?

### ISSUE THREAD

**Issue by fujeffrey1** [JakeHartnell/react-images-upload#62]
Uploading works fine but how would I reset this component after saving an image to my backend ?

**Comment by lakshmisanthi** [comment]
Did you get any solution for this?

**Comment by iamchathu** [comment]
Any Update on this?

**Comment by iamchathu** [comment]
@JakeHartnell

**Comment by ivnnv** [comment]
You should reset your state, thats nothing to do with the component itself

**Comment by iamchathu** [comment]
@ivnnv  I'm using react hooks form Controller component and it clears all other Material components but this doesn't get cleared

```ts
import { useForm, Controller } from 'react-hook-form';
...
 <Controller
          as={ImageUploader}
          name="files"
          control={control}
          withIcon={true}
          withPreview
          singleImage
          className={classes.alert}
          buttonClassName={classes.button}
          buttonText="Choose/Capture Prescription"
          label="Upload or take a picture of your image, (Max file size: 5mb, accepted: jpg, png)"
          imgExtension={['.jpg', '.png']}
          maxFileSize={5242880}
        />
```

**Comment by ivnnv** [comment]
`<Controller>` has nothing to do with this component, you should learn how internally works and make it working with the component, so this is not related to our component and ill turn off notifications from now here.

Please don't spam issues with unrelated questions, this is not stackoverflow, learn how exactly the component works.
