### ISSUE TITLE
fileContainer styles are not editable

### ISSUE THREAD

**Issue by jacobwillemsma** [JakeHartnell/react-images-upload#69]
Can't seem to drop the box shadow here from `fileContainer` class in `index.css`.

Should be able to edit these styles as with those of the button, error, etc.

Creates unsightly box:
![image](https://user-images.githubusercontent.com/4511854/44813525-f7cb8b00-aba7-11e8-94c0-8d3d24870a8f.png)

**Comment by IvanLinos** [comment]
I have sucessfully used styled-components to override any styles of the inner elements of the component. Try it.

**Comment by jacobwillemsma** [comment]
Fixed in #68

**Comment by han-so1omon** [comment]
How is this done? I can't find the prop for file container style.
Edit: Found it. It is not included in the README, nor is `style` prop
