### ISSUE TITLE
Demo link not working

### ISSUE THREAD

**Issue by mmlumba** [JakeHartnell/react-images-upload#82]
In the description the link to the demo is the following URL: https://ancient-refuge-49866.herokuapp.com/

And it leads to this screenshot:
![screen shot 2018-10-02 at 9 48 05 am](https://user-images.githubusercontent.com/4773320/46352655-501efe00-c628-11e8-934a-53297f5e2f34.png)

**Comment by JakeHartnell** [comment]
Removed the link, we should have a GitHub pages branch and just host the demo there.

**Comment by nebrelbug** [comment]
Cool-looking project, but demo link still not working. Going to a Github pages site just results in a Jekyll-themed README

**Comment by ridharezzag** [comment]
demo still not working

**Comment by anthonywebb** [comment]
^ what he said

**Comment by JakeHartnell** [comment]
https://jakehartnell.github.io/react-images-upload/
